name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  qc:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      # - run: flutter test # I don't have tests yet :3

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: qc
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build apk --debug
      - uses: actions/upload-artifact@v6
        with:
          name: android-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 5

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    needs: qc
    steps:
      - uses: actions/checkout@v6
      - run: |
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev libstdc++-12-dev
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build linux
      - uses: actions/upload-artifact@v6
        with:
          name: linux-debug
          path: build/linux/x64/debug/bundle/
          retention-days: 5

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    needs: qc
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build windows --debug
      - uses: actions/upload-artifact@v6
        with:
          name: windows-debug
          path: build/windows/runner/Debug/
          retention-days: 5
