name: Release

on:
  push:
    tags:
      - 'v*'

env:
  NO_OPUS_OGG_LIBS: 1

jobs:
  qc:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      # - run: flutter test # I don't have tests yet :3

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: qc
    
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build appbundle --release

      - uses: actions/upload-artifact@v6
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-release.apk
      # - uses: actions/upload-artifact@v6
      #   with:
      #     name: android.aab
      #     path: build/app/outputs/bundle/release/app-release.aab

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    needs: qc
    steps:
      - uses: actions/checkout@v6
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev libstdc++-12-dev
          sudo apt-get install -y libasound2-dev
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build linux --release

      - run: tar -czvf linux-release.tar.gz -C build/linux/x64/release/bundle .
      - uses: actions/upload-artifact@v6
        with:
          name: linux
          path: linux.tar.gz

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    needs: qc
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build windows --release

      - run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath windows.zip
      - uses: actions/upload-artifact@v6
        with:
          name: windows
          path: windows.zip

  build-web:
    name: Deploy Web
    runs-on: ubuntu-latest
    needs: qc
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build web --wasm --release
      - uses: actions/upload-artifact@v6
        with:
          name: web
          path: build/web/

  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    needs:
      - build-android
      - build-linux
      - build-windows
      - build-web
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "android.*,linux,windows,web"
          generateReleaseNotes: true

  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    needs: build-web
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        with:
          artifact_name: web
